// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {skill} from '../models';
import {backend} from '../models';

export function AddCategory(arg1:string):Promise<void>;

export function AddCustomTool(arg1:skill.CustomTool):Promise<void>;

export function CheckForUpdates():Promise<backend.UpdateInfo>;

export function CleanupClone(arg1:string):Promise<void>;

export function CleanupLocalTemp(arg1:string):Promise<void>;

export function ClearOperationLogs():Promise<void>;

export function CloneFromGit(arg1:string):Promise<skill.GitInstallResult>;

export function DeleteCategory(arg1:string):Promise<Array<string>>;

export function DeleteOldPath(arg1:string):Promise<void>;

export function DeleteSkill(arg1:string):Promise<void>;

export function ExportData(arg1:boolean,arg2:boolean):Promise<string>;

export function FetchSkillsLeaderboard(arg1:string):Promise<Array<backend.SkillsLeaderboardItem>>;

export function GetAllCategories():Promise<Array<skill.CategoryInfo>>;

export function GetCustomTools():Promise<Array<skill.CustomTool>>;

export function GetDetectedTools():Promise<Array<skill.ToolInfo>>;

export function GetExportInfo():Promise<backend.ExportInfo>;

export function GetLastCheckTime():Promise<string>;

export function GetMigrationInfo(arg1:string):Promise<backend.PathMigrationInfo>;

export function GetOperationLogs():Promise<Array<skill.OperationLog>>;

export function GetSettings():Promise<skill.AppSettings>;

export function GetSkill(arg1:string):Promise<skill.Skill>;

export function GetSkillHubPath():Promise<string>;

export function GetSkills():Promise<Array<skill.Skill>>;

export function GetStorageInfo():Promise<backend.StorageInfo>;

export function GetToolAdapters():Promise<Array<Record<string, any>>>;

export function GetUpdateFrequency():Promise<string>;

export function ImportData(arg1:string,arg2:boolean,arg3:boolean):Promise<void>;

export function InitializeWizard(arg1:string,arg2:Array<string>,arg3:Array<skill.CustomTool>):Promise<void>;

export function InstallFromGit(arg1:string,arg2:string,arg3:string,arg4:skill.InstallOptions):Promise<skill.Skill>;

export function InstallFromLocalTemp(arg1:string,arg2:string,arg3:string,arg4:skill.InstallOptions):Promise<skill.Skill>;

export function InstallFromPath(arg1:string,arg2:skill.InstallOptions):Promise<skill.Skill>;

export function ListSkillFiles(arg1:string,arg2:string):Promise<Array<backend.FileInfo>>;

export function MigrateData(arg1:string):Promise<void>;

export function ParseGitURL(arg1:string):Promise<backend.GitURLInfo>;

export function PreviewImportFile(arg1:string):Promise<backend.ImportPreview>;

export function ReadSkillFile(arg1:string,arg2:string):Promise<string>;

export function RemoveCustomTool(arg1:string):Promise<void>;

export function ResetAllData():Promise<void>;

export function RestartUpdateScheduler():Promise<void>;

export function SaveSettings(arg1:skill.AppSettings):Promise<void>;

export function ScanLocalPath(arg1:string):Promise<skill.LocalScanResult>;

export function ScanSkillPath(arg1:string):Promise<skill.SkillInfo>;

export function SelectFile():Promise<string>;

export function SelectFolder():Promise<string>;

export function SelectInstallFile():Promise<string>;

export function SetSkillHubPath(arg1:string):Promise<void>;

export function SetSkillHubPathWithMigration(arg1:string):Promise<void>;

export function SetUpdateFrequency(arg1:string):Promise<void>;

export function StartUpdateScheduler():Promise<void>;

export function StopUpdateScheduler():Promise<void>;

export function ToggleSkill(arg1:string,arg2:string):Promise<boolean>;

export function ToggleToolEnabled(arg1:string):Promise<void>;

export function UpdateSingleSkill(arg1:string):Promise<void>;

export function UpdateSkillMetadata(arg1:string,arg2:string,arg3:Array<string>,arg4:string):Promise<void>;

export function ValidateStoragePath(arg1:string):Promise<backend.PathValidationResult>;
