// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddCategory(arg1) {
  return window['go']['backend']['App']['AddCategory'](arg1);
}

export function AddCustomTool(arg1) {
  return window['go']['backend']['App']['AddCustomTool'](arg1);
}

export function CheckForUpdates() {
  return window['go']['backend']['App']['CheckForUpdates']();
}

export function CleanupClone(arg1) {
  return window['go']['backend']['App']['CleanupClone'](arg1);
}

export function CleanupLocalTemp(arg1) {
  return window['go']['backend']['App']['CleanupLocalTemp'](arg1);
}

export function ClearOperationLogs() {
  return window['go']['backend']['App']['ClearOperationLogs']();
}

export function CloneFromGit(arg1) {
  return window['go']['backend']['App']['CloneFromGit'](arg1);
}

export function DeleteCategory(arg1) {
  return window['go']['backend']['App']['DeleteCategory'](arg1);
}

export function DeleteOldPath(arg1) {
  return window['go']['backend']['App']['DeleteOldPath'](arg1);
}

export function DeleteSkill(arg1) {
  return window['go']['backend']['App']['DeleteSkill'](arg1);
}

export function ExportData(arg1, arg2) {
  return window['go']['backend']['App']['ExportData'](arg1, arg2);
}

export function FetchSkillsLeaderboard(arg1) {
  return window['go']['backend']['App']['FetchSkillsLeaderboard'](arg1);
}

export function GetAllCategories() {
  return window['go']['backend']['App']['GetAllCategories']();
}

export function GetCustomTools() {
  return window['go']['backend']['App']['GetCustomTools']();
}

export function GetDetectedTools() {
  return window['go']['backend']['App']['GetDetectedTools']();
}

export function GetExportInfo() {
  return window['go']['backend']['App']['GetExportInfo']();
}

export function GetLastCheckTime() {
  return window['go']['backend']['App']['GetLastCheckTime']();
}

export function GetMigrationInfo(arg1) {
  return window['go']['backend']['App']['GetMigrationInfo'](arg1);
}

export function GetOperationLogs() {
  return window['go']['backend']['App']['GetOperationLogs']();
}

export function GetSettings() {
  return window['go']['backend']['App']['GetSettings']();
}

export function GetSkill(arg1) {
  return window['go']['backend']['App']['GetSkill'](arg1);
}

export function GetSkillHubPath() {
  return window['go']['backend']['App']['GetSkillHubPath']();
}

export function GetSkills() {
  return window['go']['backend']['App']['GetSkills']();
}

export function GetStorageInfo() {
  return window['go']['backend']['App']['GetStorageInfo']();
}

export function GetToolAdapters() {
  return window['go']['backend']['App']['GetToolAdapters']();
}

export function GetUpdateFrequency() {
  return window['go']['backend']['App']['GetUpdateFrequency']();
}

export function ImportData(arg1, arg2, arg3) {
  return window['go']['backend']['App']['ImportData'](arg1, arg2, arg3);
}

export function InitializeWizard(arg1, arg2, arg3) {
  return window['go']['backend']['App']['InitializeWizard'](arg1, arg2, arg3);
}

export function InstallFromGit(arg1, arg2, arg3, arg4) {
  return window['go']['backend']['App']['InstallFromGit'](arg1, arg2, arg3, arg4);
}

export function InstallFromLocalTemp(arg1, arg2, arg3, arg4) {
  return window['go']['backend']['App']['InstallFromLocalTemp'](arg1, arg2, arg3, arg4);
}

export function InstallFromPath(arg1, arg2) {
  return window['go']['backend']['App']['InstallFromPath'](arg1, arg2);
}

export function ListSkillFiles(arg1, arg2) {
  return window['go']['backend']['App']['ListSkillFiles'](arg1, arg2);
}

export function MigrateData(arg1) {
  return window['go']['backend']['App']['MigrateData'](arg1);
}

export function ParseGitURL(arg1) {
  return window['go']['backend']['App']['ParseGitURL'](arg1);
}

export function PreviewImportFile(arg1) {
  return window['go']['backend']['App']['PreviewImportFile'](arg1);
}

export function ReadSkillFile(arg1, arg2) {
  return window['go']['backend']['App']['ReadSkillFile'](arg1, arg2);
}

export function RemoveCustomTool(arg1) {
  return window['go']['backend']['App']['RemoveCustomTool'](arg1);
}

export function ResetAllData() {
  return window['go']['backend']['App']['ResetAllData']();
}

export function RestartUpdateScheduler() {
  return window['go']['backend']['App']['RestartUpdateScheduler']();
}

export function SaveSettings(arg1) {
  return window['go']['backend']['App']['SaveSettings'](arg1);
}

export function ScanLocalPath(arg1) {
  return window['go']['backend']['App']['ScanLocalPath'](arg1);
}

export function ScanSkillPath(arg1) {
  return window['go']['backend']['App']['ScanSkillPath'](arg1);
}

export function SelectFile() {
  return window['go']['backend']['App']['SelectFile']();
}

export function SelectFolder() {
  return window['go']['backend']['App']['SelectFolder']();
}

export function SelectInstallFile() {
  return window['go']['backend']['App']['SelectInstallFile']();
}

export function SetSkillHubPath(arg1) {
  return window['go']['backend']['App']['SetSkillHubPath'](arg1);
}

export function SetSkillHubPathWithMigration(arg1) {
  return window['go']['backend']['App']['SetSkillHubPathWithMigration'](arg1);
}

export function SetUpdateFrequency(arg1) {
  return window['go']['backend']['App']['SetUpdateFrequency'](arg1);
}

export function StartUpdateScheduler() {
  return window['go']['backend']['App']['StartUpdateScheduler']();
}

export function StopUpdateScheduler() {
  return window['go']['backend']['App']['StopUpdateScheduler']();
}

export function ToggleSkill(arg1, arg2) {
  return window['go']['backend']['App']['ToggleSkill'](arg1, arg2);
}

export function ToggleToolEnabled(arg1) {
  return window['go']['backend']['App']['ToggleToolEnabled'](arg1);
}

export function UpdateSingleSkill(arg1) {
  return window['go']['backend']['App']['UpdateSingleSkill'](arg1);
}

export function UpdateSkillMetadata(arg1, arg2, arg3, arg4) {
  return window['go']['backend']['App']['UpdateSkillMetadata'](arg1, arg2, arg3, arg4);
}

export function ValidateStoragePath(arg1) {
  return window['go']['backend']['App']['ValidateStoragePath'](arg1);
}
